Repository clone-project-myplace/Backend, pull requests merged in 2023-03, with the labels that each got.

#17 Feat: #3 Spring Security 적용
  .gitignore
  build.gradle
  src/main/java/com/myplace/myplace/common/ErrorResponse.java
  src/main/java/com/myplace/myplace/common/ErrorType.java
  src/main/java/com/myplace/myplace/config/WebSecurityConfig.java
  src/main/java/com/myplace/myplace/jwt/JwtAuthFilter.java
  src/main/java/com/myplace/myplace/jwt/JwtUtil.java
  src/main/java/com/myplace/myplace/member/controller/MemberController.java
  src/main/java/com/myplace/myplace/member/entity/Member.java
  src/main/java/com/myplace/myplace/member/repository/MemberRepository.java
  src/main/java/com/myplace/myplace/member/service/MemberService.java
  src/main/java/com/myplace/myplace/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/myplace/myplace/security/UserDetailsImpl.java
  src/main/java/com/myplace/myplace/security/UserDetailsServiceImpl.java
Labels: enhancement

#19 Feat: #18 프론트와 서버 통신 테스트를 위한 API 코드 작성
  src/main/java/com/myplace/myplace/serverTest/TestController.java
  src/main/java/com/myplace/myplace/serverTest/TestResponseDto.java
  src/main/java/com/myplace/myplace/serverTest/TestService.java
Labels: enhancement

#23 Feat : #22 공통 응답 ResponseDto 구현
  src/main/java/com/myplace/myplace/common/FailureResponseDto.java
  src/main/java/com/myplace/myplace/common/MessageType.java
  src/main/java/com/myplace/myplace/common/ResponseUtils.java
  src/main/java/com/myplace/myplace/common/SuccessResponseDto.java
Labels: enhancement

#25 Feat: #4 signup 회원가입 기능 API 구현 완료
  build.gradle
  src/main/java/com/myplace/myplace/common/ErrorType.java
  src/main/java/com/myplace/myplace/config/WebSecurityConfig.java
  src/main/java/com/myplace/myplace/member/controller/MemberController.java
  src/main/java/com/myplace/myplace/member/dto/SignupRequestDto.java
  src/main/java/com/myplace/myplace/member/entity/Member.java
  src/main/java/com/myplace/myplace/member/repository/MemberRepository.java
  src/main/java/com/myplace/myplace/member/service/MemberService.java
  src/main/resources/application.yml
Labels: enhancement

#26 Feat : #24 좋아요 Entity 생성
  build.gradle
  gradlew
  src/main/java/com/myplace/myplace/like/entity/Like.java
Labels: enhancement

#27 Feat: #5 로그인 API 기능 구현 완료
  src/main/java/com/myplace/myplace/common/ErrorType.java
  src/main/java/com/myplace/myplace/member/controller/MemberController.java
  src/main/java/com/myplace/myplace/member/dto/LoginRequestDto.java
  src/main/java/com/myplace/myplace/member/service/MemberService.java
Labels: enhancement

#32 Feat: #28 음식점 Entity 생성 및 정보 저장
  src/main/java/com/myplace/myplace/restaurant/controller/RestaurantController.java
  src/main/java/com/myplace/myplace/restaurant/entity/Restaurant.java
  src/main/java/com/myplace/myplace/restaurant/repository/RestaurantRepository.java
  src/main/java/com/myplace/myplace/restaurant/service/RestaurantService.java
Labels: enhancement

#33 Chore : #30 패키지 및 import 수정
  src/main/java/com/myplace/myplace/like/entity/Like.java
  src/main/java/com/myplace/myplace/review/entity/Review.java
  src/main/java/com/myplace/myplace/review/entity/Timestamped.java
Labels: enhancement

#34 Chore : #30 리뷰 Entity 생성
  src/main/java/com/myplace/myplace/MyplaceApplication.java
  src/main/java/com/myplace/myplace/review/entity/Review.java
Labels: enhancement

#35 Chore : #30 리뷰 Entity Timestamped Import 수정
  src/main/java/com/myplace/myplace/review/entity/Review.java
Labels: enhancement

#37 Feat : #15 리뷰 좋아요 API 구현
  src/main/java/com/myplace/myplace/common/ErrorType.java
  src/main/java/com/myplace/myplace/common/MessageType.java
  src/main/java/com/myplace/myplace/like/controller/LikeController.java
  src/main/java/com/myplace/myplace/like/dto/LikeResponseDto.java
  src/main/java/com/myplace/myplace/like/repository/LikeRepository.java
  src/main/java/com/myplace/myplace/like/service/LikeService.java
  src/main/java/com/myplace/myplace/review/repository/ReviewRepository.java
Labels: enhancement

#38 Feat: #12 리뷰 작성 API 기능 구현
  src/main/java/com/myplace/myplace/common/ErrorType.java
  src/main/java/com/myplace/myplace/review/controller/ReviewController.java
  src/main/java/com/myplace/myplace/review/dto/ReviewRequestDto.java
  src/main/java/com/myplace/myplace/review/entity/Keyword.java
  src/main/java/com/myplace/myplace/review/entity/KeywordType.java
  src/main/java/com/myplace/myplace/review/entity/Review.java
  src/main/java/com/myplace/myplace/review/entity/ReviewKeyword.java
  src/main/java/com/myplace/myplace/review/repository/KeywordRepository.java
  src/main/java/com/myplace/myplace/review/repository/ReviewKeywordRepository.java
  src/main/java/com/myplace/myplace/review/service/ReviewService.java
Labels: enhancement

#39 Feat : S3 관련 파일 업로드
  src/main/java/com/myplace/myplace/FileUploadController.java
  src/main/java/com/myplace/myplace/S3Config.java
Labels: enhancement

#40 Feat : #9 방문 조회 구현
  src/main/java/com/myplace/myplace/common/MessageType.java
  src/main/java/com/myplace/myplace/visit/controller/VisitController.java
  src/main/java/com/myplace/myplace/visit/dto/VisitResponseDto.java
  src/main/java/com/myplace/myplace/visit/repository/VisitRepository.java
  src/main/java/com/myplace/myplace/visit/service/VisitService.java
Labels: enhancement

#41 #9 Feat : 방문 조회 Repository 추가
  src/main/java/com/myplace/myplace/review/repository/ReviewRepository.java
Labels: enhancement

#42 Feat: #6 프로필 사진 업로드 API 구현
  build.gradle
  src/main/java/com/myplace/myplace/FileUploadController.java
  src/main/java/com/myplace/myplace/config/WebSecurityConfig.java
  src/main/java/com/myplace/myplace/member/controller/MemberController.java
  src/main/java/com/myplace/myplace/member/dto/ProfileRequestDto.java
  src/main/java/com/myplace/myplace/member/entity/Member.java
  src/main/java/com/myplace/myplace/member/service/MemberService.java
  src/main/java/com/myplace/myplace/s3/config/S3Config.java
  src/main/java/com/myplace/myplace/s3/service/S3Uploader.java
Labels: enhancement

#43 Feat: #12 리뷰 사진 등록 기능 구현
  src/main/java/com/myplace/myplace/review/controller/ReviewController.java
  src/main/java/com/myplace/myplace/review/dto/ReviewRequestDto.java
  src/main/java/com/myplace/myplace/review/entity/Review.java
  src/main/java/com/myplace/myplace/review/service/ReviewService.java
Labels: enhancement

#44 Feat : #13 리뷰 수정 API 구현
  src/main/java/com/myplace/myplace/common/ErrorType.java
  src/main/java/com/myplace/myplace/review/controller/ReviewController.java
  src/main/java/com/myplace/myplace/review/dto/ReviewRequestDto.java
  src/main/java/com/myplace/myplace/review/dto/ReviewUpdateDto.java
  src/main/java/com/myplace/myplace/review/entity/Review.java
  src/main/java/com/myplace/myplace/review/service/ReviewService.java
Labels: enhancement

#45 Feat: #6 사용자 기본 이미지 주소 설정
  src/main/java/com/myplace/myplace/member/entity/Member.java
Labels: enhancement

#46 #8 Feat : [피드, 리뷰] 상세 조회 API 구현
  src/main/java/com/myplace/myplace/like/repository/LikeRepository.java
  src/main/java/com/myplace/myplace/review/controller/ReviewController.java
  src/main/java/com/myplace/myplace/review/dto/ReviewResponseDto.java
  src/main/java/com/myplace/myplace/review/repository/ReviewRepository.java
  src/main/java/com/myplace/myplace/review/service/ReviewService.java
Labels: enhancement

#48 Fix: #12 #13 리뷰 작성 및 수정 fix
  src/main/java/com/myplace/myplace/review/service/ReviewService.java
Labels: fix

#49 Feat: #6 S3 이미지 업로드 시 파일명 난수화
  src/main/java/com/myplace/myplace/s3/service/S3Uploader.java
Labels: enhancement

#50 Fix: 좋아요 API 요청 URL 변경 및 함수 닫기 기호 추가
  src/main/java/com/myplace/myplace/like/controller/LikeController.java
  src/main/java/com/myplace/myplace/review/controller/ReviewController.java
Labels: fix

#52 #16 Global Exception 처리 구현
  src/main/java/com/myplace/myplace/common/ErrorResponse.java
  src/main/java/com/myplace/myplace/common/GlobalExceptionHandler.java
Labels: enhancement

#53 Feat : #10 리뷰 조회 API구현
  src/main/java/com/myplace/myplace/config/WebSecurityConfig.java
  src/main/java/com/myplace/myplace/like/entity/Like.java
  src/main/java/com/myplace/myplace/like/repository/LikeRepository.java
  src/main/java/com/myplace/myplace/review/controller/ReviewController.java
  src/main/java/com/myplace/myplace/review/dto/ReviewRequestDto.java
  src/main/java/com/myplace/myplace/review/dto/ReviewResponseDto.java
  src/main/java/com/myplace/myplace/review/repository/ReviewRepository.java
  src/main/java/com/myplace/myplace/review/service/ReviewService.java
  src/main/java/com/myplace/myplace/visit/controller/VisitController.java
Labels: enhancement

#55 Feat: #7 피드 리뷰 전체 조회 API 기능 구현
  src/main/java/com/myplace/myplace/common/ErrorType.java
  src/main/java/com/myplace/myplace/review/controller/ReviewController.java
  src/main/java/com/myplace/myplace/review/dto/FeedPageResponseDto.java
  src/main/java/com/myplace/myplace/review/dto/FeedReviewResponseDto.java
  src/main/java/com/myplace/myplace/review/repository/ReviewRepository.java
  src/main/java/com/myplace/myplace/review/service/ReviewService.java
Labels: enhancement

#56 Chore : #9 service 변경
  src/main/java/com/myplace/myplace/visit/service/VisitService.java
Labels: enhancement

#57 Feat: #16 예외처리 추가
  src/main/java/com/myplace/myplace/common/ErrorResponse.java
  src/main/java/com/myplace/myplace/common/GlobalExceptionHandler.java
Labels: enhancement

#59 Refactor: #22 공통 응답 필드 값 null인 경우 처리 및 리뷰 컬럼 타입 변경
  src/main/java/com/myplace/myplace/common/SuccessResponseDto.java
  src/main/java/com/myplace/myplace/review/entity/Review.java
Labels: refactor

#60 Feat: #5 로그인 response 구현
  src/main/java/com/myplace/myplace/member/controller/MemberController.java
  src/main/java/com/myplace/myplace/member/dto/LoginResponseDto.java
  src/main/java/com/myplace/myplace/member/service/MemberService.java
Labels: enhancement

#61 Fix: Entity DDL 관련 수정
  src/main/java/com/myplace/myplace/review/entity/Review.java
  src/main/java/com/myplace/myplace/review/entity/ReviewKeyword.java
Labels: fix

#63 Fix: #14 리뷰 삭제시 저장된 좋아요 함께 삭제
  src/main/java/com/myplace/myplace/like/repository/LikeRepository.java
  src/main/java/com/myplace/myplace/review/service/ReviewService.java
Labels: fix

#64 Fix: #9 방문 조회 시 리뷰 작성 여부 확인 수정
  src/main/java/com/myplace/myplace/review/repository/ReviewRepository.java
  src/main/java/com/myplace/myplace/visit/service/VisitService.java
Labels: fix

#65 Chore : #12 키워드 수정
  src/main/java/com/myplace/myplace/review/entity/KeywordType.java
Labels: fix

#66 Feat : #15 리뷰 좋아요 반환 값 추가
  src/main/java/com/myplace/myplace/like/dto/LikeResponseDto.java
  src/main/java/com/myplace/myplace/like/service/LikeService.java
Labels: enhancement

#67 Feat: #7 전체 피드 조회 시, 유저가 리뷰에 좋아요 눌렀는지 여부 확인
  src/main/java/com/myplace/myplace/like/repository/LikeRepository.java
  src/main/java/com/myplace/myplace/review/controller/ReviewController.java
  src/main/java/com/myplace/myplace/review/dto/FeedReviewResponseDto.java
  src/main/java/com/myplace/myplace/review/service/ReviewService.java
Labels: enhancement

#68 Feat : #8 좋아요 관련 기능 추가
  src/main/java/com/myplace/myplace/review/controller/ReviewController.java
  src/main/java/com/myplace/myplace/review/dto/ReviewDetailDto.java
  src/main/java/com/myplace/myplace/review/service/ReviewService.java
Labels: enhancement

#70 Readme 업데이트
  README.md
  document/api.png
  document/erd.png
  document/와이어프레임.pdf
Labels: documentation

#71 Chore : #8 데이터 추가
  src/main/java/com/myplace/myplace/config/WebSecurityConfig.java
  src/main/java/com/myplace/myplace/review/dto/ReviewDetailDto.java
  src/main/java/com/myplace/myplace/review/service/ReviewService.java
  src/main/java/com/myplace/myplace/serverTest/TestController.java
  src/main/java/com/myplace/myplace/serverTest/TestService.java
Labels: fix

#72 Feat : #31 https 서버 배포
  src/main/java/com/myplace/myplace/MyplaceApplication.java
Labels: enhancement

#73 Fix: #9 작성한 리뷰가 있는 경우 조건문 수정 및 미로그인 처리
  src/main/java/com/myplace/myplace/visit/controller/VisitController.java
  src/main/java/com/myplace/myplace/visit/service/VisitService.java
Labels: fix

#74 Chore : #10 [리뷰]리뷰 조회 수정
  src/main/java/com/myplace/myplace/review/controller/ReviewController.java
  src/main/java/com/myplace/myplace/review/service/ReviewService.java
Labels: fix

#76 Feat: #7 피드 전체 조회 시 사용자 프로필 이미지 리턴
  src/main/java/com/myplace/myplace/review/dto/FeedPageResponseDto.java
  src/main/java/com/myplace/myplace/review/service/ReviewService.java
Labels: enhancement

#77 Feat: #6 프로필 이미지 등록 후 수정된 img url 리턴
  src/main/java/com/myplace/myplace/member/controller/MemberController.java
  src/main/java/com/myplace/myplace/member/dto/ProfileResponseDto.java
  src/main/java/com/myplace/myplace/member/service/MemberService.java
Labels: enhancement

#78 Chore : #8 상세 조회 코드 추가
  src/main/java/com/myplace/myplace/review/dto/ReviewDetailDto.java
Labels: fix

#79 Chore : #13 리뷰 수정 코드 수정
  src/main/java/com/myplace/myplace/review/controller/ReviewController.java
Labels: fix

#80 Chore : #13 리뷰 수정 코드 수정
  src/main/java/com/myplace/myplace/review/dto/ReviewUpdateDto.java
Labels: fix

#82 Feat: #81 로그인 사용자 정보 조회 API 구현
  src/main/java/com/myplace/myplace/member/controller/MemberController.java
  src/main/java/com/myplace/myplace/member/dto/MemberInfoResponseDto.java
  src/main/java/com/myplace/myplace/member/service/MemberService.java
Labels: enhancement

#83 Feat: #81 로그인 사용자 정보 조회 시 작성 리뷰 개수 리턴
  src/main/java/com/myplace/myplace/member/dto/MemberInfoResponseDto.java
  src/main/java/com/myplace/myplace/member/service/MemberService.java
  src/main/java/com/myplace/myplace/review/repository/ReviewRepository.java
Labels: enhancement

#84 Docs: README.md 업데이트
  README.md
Labels: documentation
